kind: Service
apiVersion: v1
metadata:
  name: haproxy
  namespace: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: status
      protocol: TCP
      port: 1936
      targetPort: 1936
      nodePort: 32047
    - name: replication
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30012
  internalTrafficPolicy: Cluster
  type: NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: haproxy
